import { MigrationInterface, QueryRunner } from 'typeorm';

export class InitialMigration1733805538293 implements MigrationInterface {
  name = 'InitialMigration1733805538293';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`ARQUIVOS\` (\`ARQ_ID\` int NOT NULL AUTO_INCREMENT, \`ARQ_ARQUIVO\` mediumblob NOT NULL, PRIMARY KEY (\`ARQ_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`CENARIOS\` (\`CEN_ID\` int NOT NULL AUTO_INCREMENT, \`CEN_NOME\` varchar(50) NOT NULL, \`CEN_DESCRICAO\` varchar(255) NOT NULL, \`CEN_TIPO\` enum ('PRINCIPAL', 'ALTERNATIVO') NOT NULL DEFAULT 'PRINCIPAL', \`FK_CASOS_DE_USO_CAS_ID\` int NULL, PRIMARY KEY (\`CEN_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`ATORES\` (\`ATO_ID\` int NOT NULL AUTO_INCREMENT, \`ATO_NOME\` varchar(30) NOT NULL, \`ATO_COMPLEXIDADE\` enum ('SIMPLES', 'MEDIO', 'COMPLEXO') NOT NULL DEFAULT 'SIMPLES', \`ATO_DESCRICAO\` varchar(255) NOT NULL, \`FK_PROJETOS_PRO_ID\` int NULL, PRIMARY KEY (\`ATO_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`STATUS_PRIORIZACAO\` (\`SPA_ID\` int NOT NULL AUTO_INCREMENT, \`SPA_PARTICIPACAO_REALIZADA\` tinyint NOT NULL DEFAULT 0, \`SPA_ALERTA_EMITIDO\` tinyint NOT NULL DEFAULT 0, \`FK_STAKEHOLDERS_STA_ID\` int NULL, \`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\` int NULL, PRIMARY KEY (\`SPA_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`USUARIOS\` (\`USU_ID\` int NOT NULL AUTO_INCREMENT, \`USU_DATA_CADASTRO\` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`USU_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`COLABORADORES_PROJETOS\` (\`COP_ID\` int NOT NULL AUTO_INCREMENT, \`COP_ATIVO\` tinyint NOT NULL, \`COP_ADMINISTRADOR\` tinyint NOT NULL, \`FK_COLABORADORES_COL_ID\` int NULL, \`FK_COLABORADORES_FK_USUARIOS_USU_ID\` int NULL, \`FK_PROJETOS_PRO_ID\` int NULL, PRIMARY KEY (\`COP_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`ESTIMATIVAS_ESFORCOS\` (\`EST_ID\` int NOT NULL AUTO_INCREMENT, \`EST_RESULTADO_HORAS\` double(8,2) NOT NULL, \`EST_PESO_ATORES\` int NOT NULL, \`EST_PESO_CASOS_USO\` int NOT NULL, \`EST_PESO_PONTOS_CASOS_USO\` int NOT NULL, \`EST_TFACTOR\` double(6,3) NOT NULL, \`EST_EFACTOR\` double(6,3) NOT NULL, \`EST_RESULTADO_PONTOS_CASOS_USO\` double(6,3) NOT NULL, \`EST_DATA_ESTIMATIVA\` varchar(20) NOT NULL, \`projetoId\` int NULL, PRIMARY KEY (\`EST_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`FATORES_AMBIENTAIS\` (\`AMB_ID\` int NOT NULL AUTO_INCREMENT, \`AMB_DESCRICAO\` varchar(255) NOT NULL, \`AMB_PESO\` double(4,2) NOT NULL, PRIMARY KEY (\`AMB_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`FATORES_AMBIENTAIS_PROJETOS\` (\`AMP_ID\` int NOT NULL AUTO_INCREMENT, \`AMP_VALOR\` int NOT NULL, \`FK_PROJETOS_PRO_ID\` int NULL, \`FK_FATORES_AMBIENTAIS_AMB_ID\` int NULL, PRIMARY KEY (\`AMP_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`FATORES_TECNICOS\` (\`TEC_ID\` int NOT NULL AUTO_INCREMENT, \`TEC_DESCRICAO\` varchar(50) NOT NULL, \`TEC_PESO\` double(4,2) NOT NULL, PRIMARY KEY (\`TEC_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`FATORES_TECNICOS_PROJETOS\` (\`TEP_ID\` int NOT NULL AUTO_INCREMENT, \`TEP_VALOR\` int NOT NULL, \`FK_PROJETOS_PRO_ID\` int NULL, \`FK_FATORES_TECNICOS_TEC_ID\` int NULL, PRIMARY KEY (\`TEP_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`SPRINTS\` (\`SPR_ID\` int NOT NULL AUTO_INCREMENT, \`SPR_NOME\` varchar(30) NOT NULL, \`SPR_DESCRICAO\` varchar(255) NOT NULL, \`SPR_HORAS_PREVISTAS\` int NOT NULL, \`SPR_DATA_INICIO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`SPR_DATA_FIM\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`SPR_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`SUITES_DE_TESTE\` (\`id\` int NOT NULL AUTO_INCREMENT, \`SDT_NOME\` varchar(50) NOT NULL, \`SDT_STATUS\` enum ('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO', \`SDT_DESCRICAO\` varchar(255) NOT NULL, \`SDT_OBSERVACOES\` varchar(255) NOT NULL, \`SDT_DATA_CRIACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`SDT_DATA_ATUALIZACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`SDT_DATA_EXCLUSAO\` datetime(6) NULL, \`FK_SUITE_DE_TESTE_SDT_ID\` int NULL, \`FK_PROJETO_PRO_ID\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`PROJETOS\` (\`PRO_ID\` int NOT NULL AUTO_INCREMENT, \`PRO_NOME\` varchar(100) NOT NULL, \`PRO_DESCRICAO\` varchar(255) NOT NULL, \`PRO_EMPRESA\` varchar(50) NOT NULL, \`PRO_DATA_INICIO\` date NOT NULL, \`PRO_PREVISAO_FIM\` date NOT NULL, \`PRO_STATUS\` enum ('EM ANDAMENTO', 'FINALIZADO', 'CANCELADO') NOT NULL DEFAULT 'EM ANDAMENTO', \`PRO_RESTFACTOR\` double(4,2) NULL, \`PRO_RESEFACTOR\` double(4,2) NULL, PRIMARY KEY (\`PRO_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`STAKEHOLDERS\` (\`STA_ID\` int NOT NULL AUTO_INCREMENT, \`STA_CHAVE\` varchar(100) NOT NULL, \`STA_SENHA\` varchar(100) NOT NULL, \`STA_NOME\` varchar(100) NOT NULL, \`STA_CARGO\` varchar(50) NOT NULL, \`STA_EMAIL\` varchar(255) NOT NULL, \`FK_USUARIOS_USU_ID\` int NULL, \`FK_PROJETOS_PRO_ID\` int NULL, PRIMARY KEY (\`STA_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`PRIORIZACAO_STAKEHOLDERS\` (\`PRS_ID\` int NOT NULL AUTO_INCREMENT, \`PRS_CLASSIFICACAO_REQUISITO\` enum ('DEVE SER FEITO', 'PERFORMANCE', 'ATRATIVO', 'INDIFERENTE', 'QUESTIONAVEL', 'REVERSO') NOT NULL, \`PRS_RESPOSTA_POSITIVA\` enum ('GOSTARIA', 'ESPERADO', 'NAO IMPORTA', 'CONVIVO COM ISSO', 'NAO GOSTARIA') NOT NULL, \`PRS_RESPOSTA_NEGATIVA\` enum ('GOSTARIA', 'ESPERADO', 'NAO IMPORTA', 'CONVIVO COM ISSO', 'NAO GOSTARIA') NOT NULL, \`FK_STAKEHOLDERS_STA_ID\` int NULL, \`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\` int NULL, \`FK_REQUISITOS_FUNCIONAIS_REQ_ID\` int NULL, PRIMARY KEY (\`PRS_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`RESULTADO_REQUISITOS\` (\`RPR_ID\` int NOT NULL AUTO_INCREMENT, \`RPR_RESULTADO_FINAL\` enum ('DEVE SER FEITO', 'PERFORMANCE', 'ATRATIVO', 'INDIFERENTE', 'QUESTIONAVEL', 'REVERSO') NOT NULL, \`FK_REQUISITOS_FUNCIONAIS_REQ_ID\` int NULL, PRIMARY KEY (\`RPR_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`REQUISITOS_FUNCIONAIS\` (\`REQ_ID\` int NOT NULL AUTO_INCREMENT, \`REQ_ESPECIFICACAO\` varchar(1000) NOT NULL, \`REQ_NOME\` varchar(100) NOT NULL, \`REQ_NUMERO_IDENTIFICADOR\` int NOT NULL, \`FK_PROJETOS_PRO_ID\` int NULL, PRIMARY KEY (\`REQ_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`CASOS_DE_USO\` (\`CAS_ID\` int NOT NULL AUTO_INCREMENT, \`CAS_NOME\` varchar(50) NOT NULL, \`CAS_DESCRICAO\` varchar(255) NOT NULL, \`CAS_COMPLEXIDADE\` enum ('SIMPLES', 'MEDIO', 'COMPLEXO') NOT NULL DEFAULT 'SIMPLES', \`FK_REQUISITOS_FUNCIONAIS_REQ_ID\` int NULL, PRIMARY KEY (\`CAS_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`EXECUCOES_DE_TESTE\` (\`EDT_ID\` int NOT NULL AUTO_INCREMENT, \`EDT_NOME\` varchar(50) NOT NULL, \`EDT_DATA_EXECUCAO\` timestamp NOT NULL, \`EDT_RESPOSTA\` varchar(255) NULL, \`EDT_RESULTADO\` enum ('SUCESSO', 'FALHA', 'PENDENTE') NOT NULL DEFAULT 'PENDENTE', \`EDT_OBSERVACAO\` varchar(255) NULL, \`EDT_METODO\` enum ('MANUAL', 'AUTOMATIZADO') NOT NULL DEFAULT 'MANUAL', \`EDT_DATA_CRIACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`EDT_DATA_ATUALIZACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`EDT_DATA_EXCLUSAO\` datetime(6) NULL, \`FK_CASO_DE_TESTE_CDT_ID\` int NULL, PRIMARY KEY (\`EDT_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`CASOS_DE_TESTE\` (\`CDT_ID\` int NOT NULL AUTO_INCREMENT, \`CDT_NOME\` varchar(50) NOT NULL, \`CDT_STATUS\` enum ('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO', \`CDT_METODO\` enum ('MANUAL', 'AUTOMATIZADO') NOT NULL DEFAULT 'MANUAL', \`CDT_TECNICA\` enum ('FUNCIONAL', 'ESTRUTURAL') NOT NULL DEFAULT 'FUNCIONAL', \`CDT_PRIORIDADE\` enum ('ALTA', 'MEDIA', 'BAIXA') NOT NULL DEFAULT 'MEDIA', \`CDT_COMPLEXIDADE\` enum ('SIMPLES', 'MEDIO', 'COMPLEXO') NOT NULL DEFAULT 'SIMPLES', \`CDT_DESCRICAO\` varchar(255) NOT NULL, \`CDT_OBSERVACOES\` varchar(255) NOT NULL, \`CDT_PRE_CONDICAO\` varchar(255) NOT NULL, \`CDT_POS_CONDICAO\` varchar(255) NOT NULL, \`CDT_DADOS_ENTRADA\` text NOT NULL, \`CDT_RESULTADO_ESPERADO\` text NOT NULL, \`CDT_DATA_CRIACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`CDT_DATA_ATUALIZACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`CDT_DATA_EXCLUSAO\` datetime(6) NULL, \`FK_CASOS_DE_USO_CAS_ID\` int NULL, \`FK_SUITE_DE_TESTE_SDT_ID\` int NULL, \`FK_COLABORADORES_COL_ID\` int NULL, \`FK_PROJETO_PRO_ID\` int NULL, PRIMARY KEY (\`CDT_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`COMENTARIOS\` (\`CMN_ID\` int NOT NULL AUTO_INCREMENT, \`CMN_COMENTARIO\` varchar(255) NOT NULL, \`CMN_CRIADO_EM\` datetime NOT NULL, \`CMN_MODIFICADO_EM\` datetime NOT NULL, \`FK_USUARIO_ID\` int NULL, \`FK_USER_STORY\` int NULL, PRIMARY KEY (\`CMN_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`COLABORADORES\` (\`COL_ID\` int NOT NULL AUTO_INCREMENT, \`COL_NOME\` varchar(100) NOT NULL, \`COL_EMAIL\` varchar(255) NOT NULL, \`COL_SENHA\` varchar(100) NOT NULL, \`COL_EMPRESA\` varchar(30) NOT NULL, \`COL_CARGO\` enum ('Gerente de Projeto', 'Analista de Sistemas', 'Desenvolvedor', 'Product Owner', 'Scrum Master') NOT NULL DEFAULT 'Desenvolvedor', \`FK_USUARIOS_USU_ID\` int NULL, PRIMARY KEY (\`COL_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`SWIMLANES\` (\`SWI_ID\` int NOT NULL AUTO_INCREMENT, \`SWI_NOME\` varchar(30) NOT NULL, \`SWI_VERTICAL\` tinyint(1) NOT NULL DEFAULT '0', \`SWI_COR\` varchar(7) NOT NULL, \`SWI_CRIADO_EM\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`SWI_ATUALIZADO_EM\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`FK_KAN_ID\` int NULL, PRIMARY KEY (\`SWI_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`KANBANS\` (\`KAN_ID\` int NOT NULL AUTO_INCREMENT, \`FK_PRO_ID\` int NULL, UNIQUE INDEX \`REL_7b35d1df7f716ff30c825ce989\` (\`FK_PRO_ID\`), PRIMARY KEY (\`KAN_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`SUBTAREFAS\` (\`SBT_ID\` int NOT NULL AUTO_INCREMENT, \`SBT_DESCRICAO\` varchar(255) NOT NULL, \`SBT_COMPLETADA\` tinyint(1) NOT NULL, \`FK_USER_STORY\` int NULL, PRIMARY KEY (\`SBT_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`TAGS\` (\`TAG_ID\` int NOT NULL AUTO_INCREMENT, \`TAG_NOME\` varchar(20) NOT NULL, \`TAG_COR\` varchar(6) NOT NULL, PRIMARY KEY (\`TAG_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`USER_STORIES\` (\`UST_ID\` int NOT NULL AUTO_INCREMENT, \`UST_TITULO\` varchar(50) NOT NULL, \`UST_DESCRICAO\` varchar(255) NOT NULL, \`UST_ESTIMATIVA_TEMPO\` int NOT NULL, \`UST_CRIADO_EM\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`UST_MODIFICADO_EM\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`FK_COLABORADOR_COL_CRI_ID\` int NULL, \`FK_COLABORADOR_COL_RES_ID\` int NULL, \`FK_KANBAN_ID\` int NULL, \`FK_PRO_ID\` int NULL, \`FK_SWI_ID\` int NULL, PRIMARY KEY (\`UST_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`USER_STORY_ARQUIVOS\` (\`uSERSTORIESUSTID\` int NOT NULL, \`aRQUIVOSArqId\` int NOT NULL, INDEX \`IDX_17071da5d078578dc872197749\` (\`uSERSTORIESUSTID\`), INDEX \`IDX_f8a81b2401c309e707d8762768\` (\`aRQUIVOSArqId\`), PRIMARY KEY (\`uSERSTORIESUSTID\`, \`aRQUIVOSArqId\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`USER_STORIES_COLABORADORES\` (\`uSERSTORIESUSTID\` int NOT NULL, \`cOLABORADORESCOLID\` int NOT NULL, INDEX \`IDX_3500f15e563669a9d11db7fa37\` (\`uSERSTORIESUSTID\`), INDEX \`IDX_848e3adaa61749ce5f87199290\` (\`cOLABORADORESCOLID\`), PRIMARY KEY (\`uSERSTORIESUSTID\`, \`cOLABORADORESCOLID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`SPRINTS_USERS_STORIES\` (\`uSERSTORIESUSTID\` int NOT NULL, \`sPRINTSSPRID\` int NOT NULL, INDEX \`IDX_a914f1497fdc7f03ac8a40af0a\` (\`uSERSTORIESUSTID\`), INDEX \`IDX_b878609198e33979b5cab65169\` (\`sPRINTSSPRID\`), PRIMARY KEY (\`uSERSTORIESUSTID\`, \`sPRINTSSPRID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`SUITES_DE_TESTE_RELATION_closure\` (\`id_ancestor\` int NOT NULL, \`id_descendant\` int NOT NULL, INDEX \`IDX_7a69302bc35bf787fd17ea067f\` (\`id_ancestor\`), INDEX \`IDX_0a663735b1c11c6dfa3ead92b9\` (\`id_descendant\`), PRIMARY KEY (\`id_ancestor\`, \`id_descendant\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CENARIOS\` ADD CONSTRAINT \`FK_A680E32F58A0D62135D90EC600B\` FOREIGN KEY (\`FK_CASOS_DE_USO_CAS_ID\`) REFERENCES \`CASOS_DE_USO\`(\`CAS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ATORES\` ADD CONSTRAINT \`FK_B3DDC2A92CAA7C6D1386A1C378B\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_4E3922310803560CBA80659F279\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_FB7231B4EB38AC98B4BE32C3C7B\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_A2F3842C6D1E9DA85BE63795669\` FOREIGN KEY (\`FK_COLABORADORES_COL_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_671BAB7EC79797879138366A686\` FOREIGN KEY (\`FK_COLABORADORES_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_21D329DC2438A0D5CE536A3D356\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ESTIMATIVAS_ESFORCOS\` ADD CONSTRAINT \`FK_D8A1435775F634E45757FECC3D5\` FOREIGN KEY (\`projetoId\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` ADD CONSTRAINT \`FK_33547206E5E9D4AEEBBE967B604\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` ADD CONSTRAINT \`FK_831BB9A8AB96127713017B69A29\` FOREIGN KEY (\`FK_FATORES_AMBIENTAIS_AMB_ID\`) REFERENCES \`FATORES_AMBIENTAIS\`(\`AMB_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` ADD CONSTRAINT \`FK_41F07677E6F8179942791B2C299\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` ADD CONSTRAINT \`FK_6F81EC50A173807E18B6C813777\` FOREIGN KEY (\`FK_FATORES_TECNICOS_TEC_ID\`) REFERENCES \`FATORES_TECNICOS\`(\`TEC_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` ADD CONSTRAINT \`FK_9CBCD836FC4F159AC7E7CA68137\` FOREIGN KEY (\`FK_SUITE_DE_TESTE_SDT_ID\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` ADD CONSTRAINT \`FK_B6277B122D6885971D6DFD0AD95\` FOREIGN KEY (\`FK_PROJETO_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` ADD CONSTRAINT \`FK_3733A295E8F3C4E6F23F3BABC2E\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` ADD CONSTRAINT \`FK_62BC9443115B976B578B5E37DC0\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_2672110843A47157079202A5CF7\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_18C191A2937D73B149EB6F86597\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_26F5CBA11CC26D82765CC57EAFE\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`RESULTADO_REQUISITOS\` ADD CONSTRAINT \`FK_8B08CF83FFD1E3F815C8B45B6FE\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`REQUISITOS_FUNCIONAIS\` ADD CONSTRAINT \`FK_1670334E6CB5E4A12AE45517CC7\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_USO\` ADD CONSTRAINT \`FK_0ECBAA9A062F7A4FBFDD15C9902\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`EXECUCOES_DE_TESTE\` ADD CONSTRAINT \`FK_8814CAE507F613801943E0D7F6C\` FOREIGN KEY (\`FK_CASO_DE_TESTE_CDT_ID\`) REFERENCES \`CASOS_DE_TESTE\`(\`CDT_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_B4366658430072A75E6767EC866\` FOREIGN KEY (\`FK_CASOS_DE_USO_CAS_ID\`) REFERENCES \`CASOS_DE_USO\`(\`CAS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_BB77D73B65984173FDAD8081EA8\` FOREIGN KEY (\`FK_SUITE_DE_TESTE_SDT_ID\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_C605514B9A8B8C7D1F0368AB195\` FOREIGN KEY (\`FK_COLABORADORES_COL_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_A4806D23A33189C705EEC34FFAC\` FOREIGN KEY (\`FK_PROJETO_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` ADD CONSTRAINT \`FK_344F8118376D5A82E4ECB4D4923\` FOREIGN KEY (\`FK_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` ADD CONSTRAINT \`FK_1B34F167EB645F5ED4C44D9444E\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES\` ADD CONSTRAINT \`FK_65A1F543DDC8B9A47B0E403CAA6\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` ADD CONSTRAINT \`FK_58AAF08431B217DC3845C78DA5F\` FOREIGN KEY (\`FK_KAN_ID\`) REFERENCES \`KANBANS\`(\`KAN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`KANBANS\` ADD CONSTRAINT \`FK_7B35D1DF7F716FF30C825CE9897\` FOREIGN KEY (\`FK_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` ADD CONSTRAINT \`FK_B4640DA6FEB4E19EFFBF3E6DF9E\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_48311CE7E29574D5CBE2E57DE23\` FOREIGN KEY (\`FK_COLABORADOR_COL_CRI_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_28A13D2B8B6E2907E9F73B0812E\` FOREIGN KEY (\`FK_COLABORADOR_COL_RES_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_6108264AC009132260079873F8C\` FOREIGN KEY (\`FK_KANBAN_ID\`) REFERENCES \`KANBANS\`(\`KAN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_009516F3B82AF76B34016A8AF11\` FOREIGN KEY (\`FK_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_F67D042A43CA9187F6FFBBA1BBD\` FOREIGN KEY (\`FK_SWI_ID\`) REFERENCES \`SWIMLANES\`(\`SWI_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` ADD CONSTRAINT \`FK_17071DA5D078578DC872197749C\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` ADD CONSTRAINT \`FK_F8A81B2401C309E707D8762768E\` FOREIGN KEY (\`aRQUIVOSArqId\`) REFERENCES \`ARQUIVOS\`(\`ARQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` ADD CONSTRAINT \`FK_3500F15E563669A9D11DB7FA376\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` ADD CONSTRAINT \`FK_848E3ADAA61749CE5F871992906\` FOREIGN KEY (\`cOLABORADORESCOLID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` ADD CONSTRAINT \`FK_A914F1497FDC7F03AC8A40AF0A1\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` ADD CONSTRAINT \`FK_B878609198E33979B5CAB651694\` FOREIGN KEY (\`sPRINTSSPRID\`) REFERENCES \`SPRINTS\`(\`SPR_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` ADD CONSTRAINT \`FK_7A69302BC35BF787FD17EA067F9\` FOREIGN KEY (\`id_ancestor\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` ADD CONSTRAINT \`FK_0A663735B1C11C6DFA3EAD92B9D\` FOREIGN KEY (\`id_descendant\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('1','Familiaridade com o processo unificado', '1.5')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('2','Experiência aplicação', '0.5')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('3','Experiência com orientação a objetos', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('4','Capacidade de análise do líder de projeto', '0.5')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('5','Motivação', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('6','Estabilidade dos requisitos', '2.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('7','Consultores em tempo parcial', '-1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_AMBIENTAIS\` (\`AMB_ID\`,\`AMB_DESCRICAO\`, \`AMB_PESO\`) VALUES ('8','Dificuldade de programação na Linguagem', '-1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('1','Sistema distribuído', '2.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('2','Desempenho da Aplicação', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('3','Eficiência do Usuário', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('4','Complexidade de Processamento', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('5','Reusabilidade de Código', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('6','Facilidade de instalação', '0.5')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('7','Facilidade de uso', '0.5')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('8','Portabilidade', '2.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('9','Facilidade de mudança', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('10','Concorrência', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('11','Características de segurança', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('12','Acesso a Dispositivos de Terceiros', '1.0')`,
    );
    await queryRunner.query(
      `INSERT INTO \`FATORES_TECNICOS\` (\`TEC_ID\`,\`TEC_DESCRICAO\`, \`TEC_PESO\`) VALUES ('13','Requer Treinamento aos Usuários', '1.0')`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` DROP FOREIGN KEY \`FK_0A663735B1C11C6DFA3EAD92B9D\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` DROP FOREIGN KEY \`FK_7A69302BC35BF787FD17EA067F9\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` DROP FOREIGN KEY \`FK_B878609198E33979B5CAB651694\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` DROP FOREIGN KEY \`FK_A914F1497FDC7F03AC8A40AF0A1\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` DROP FOREIGN KEY \`FK_848E3ADAA61749CE5F871992906\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` DROP FOREIGN KEY \`FK_3500F15E563669A9D11DB7FA376\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` DROP FOREIGN KEY \`FK_F8A81B2401C309E707D8762768E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` DROP FOREIGN KEY \`FK_17071DA5D078578DC872197749C\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_F67D042A43CA9187F6FFBBA1BBD\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_009516F3B82AF76B34016A8AF11\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_6108264AC009132260079873F8C\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_28A13D2B8B6E2907E9F73B0812E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_48311CE7E29574D5CBE2E57DE23\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` DROP FOREIGN KEY \`FK_B4640DA6FEB4E19EFFBF3E6DF9E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`KANBANS\` DROP FOREIGN KEY \`FK_7B35D1DF7F716FF30C825CE9897\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` DROP FOREIGN KEY \`FK_58AAF08431B217DC3845C78DA5F\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES\` DROP FOREIGN KEY \`FK_65A1F543DDC8B9A47B0E403CAA6\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` DROP FOREIGN KEY \`FK_1B34F167EB645F5ED4C44D9444E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` DROP FOREIGN KEY \`FK_344F8118376D5A82E4ECB4D4923\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_A4806D23A33189C705EEC34FFAC\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_C605514B9A8B8C7D1F0368AB195\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_BB77D73B65984173FDAD8081EA8\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_B4366658430072A75E6767EC866\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`EXECUCOES_DE_TESTE\` DROP FOREIGN KEY \`FK_8814CAE507F613801943E0D7F6C\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_USO\` DROP FOREIGN KEY \`FK_0ECBAA9A062F7A4FBFDD15C9902\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`REQUISITOS_FUNCIONAIS\` DROP FOREIGN KEY \`FK_1670334E6CB5E4A12AE45517CC7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`RESULTADO_REQUISITOS\` DROP FOREIGN KEY \`FK_8B08CF83FFD1E3F815C8B45B6FE\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_26F5CBA11CC26D82765CC57EAFE\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_18C191A2937D73B149EB6F86597\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_2672110843A47157079202A5CF7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` DROP FOREIGN KEY \`FK_62BC9443115B976B578B5E37DC0\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` DROP FOREIGN KEY \`FK_3733A295E8F3C4E6F23F3BABC2E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` DROP FOREIGN KEY \`FK_B6277B122D6885971D6DFD0AD95\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` DROP FOREIGN KEY \`FK_9CBCD836FC4F159AC7E7CA68137\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` DROP FOREIGN KEY \`FK_6F81EC50A173807E18B6C813777\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` DROP FOREIGN KEY \`FK_41F07677E6F8179942791B2C299\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` DROP FOREIGN KEY \`FK_831BB9A8AB96127713017B69A29\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` DROP FOREIGN KEY \`FK_33547206E5E9D4AEEBBE967B604\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ESTIMATIVAS_ESFORCOS\` DROP FOREIGN KEY \`FK_D8A1435775F634E45757FECC3D5\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_21D329DC2438A0D5CE536A3D356\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_671BAB7EC79797879138366A686\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_A2F3842C6D1E9DA85BE63795669\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_FB7231B4EB38AC98B4BE32C3C7B\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_4E3922310803560CBA80659F279\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ATORES\` DROP FOREIGN KEY \`FK_B3DDC2A92CAA7C6D1386A1C378B\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CENARIOS\` DROP FOREIGN KEY \`FK_A680E32F58A0D62135D90EC600B\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_0a663735b1c11c6dfa3ead92b9\` ON \`SUITES_DE_TESTE_RELATION_closure\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_7a69302bc35bf787fd17ea067f\` ON \`SUITES_DE_TESTE_RELATION_closure\``,
    );
    await queryRunner.query(`DROP TABLE \`SUITES_DE_TESTE_RELATION_closure\``);
    await queryRunner.query(
      `DROP INDEX \`IDX_b878609198e33979b5cab65169\` ON \`SPRINTS_USERS_STORIES\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_a914f1497fdc7f03ac8a40af0a\` ON \`SPRINTS_USERS_STORIES\``,
    );
    await queryRunner.query(`DROP TABLE \`SPRINTS_USERS_STORIES\``);
    await queryRunner.query(
      `DROP INDEX \`IDX_848e3adaa61749ce5f87199290\` ON \`USER_STORIES_COLABORADORES\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_3500f15e563669a9d11db7fa37\` ON \`USER_STORIES_COLABORADORES\``,
    );
    await queryRunner.query(`DROP TABLE \`USER_STORIES_COLABORADORES\``);
    await queryRunner.query(
      `DROP INDEX \`IDX_f8a81b2401c309e707d8762768\` ON \`USER_STORY_ARQUIVOS\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_17071da5d078578dc872197749\` ON \`USER_STORY_ARQUIVOS\``,
    );
    await queryRunner.query(`DROP TABLE \`USER_STORY_ARQUIVOS\``);
    await queryRunner.query(`DROP TABLE \`USER_STORIES\``);
    await queryRunner.query(`DROP TABLE \`TAGS\``);
    await queryRunner.query(`DROP TABLE \`SUBTAREFAS\``);
    await queryRunner.query(
      `DROP INDEX \`REL_7b35d1df7f716ff30c825ce989\` ON \`KANBANS\``,
    );
    await queryRunner.query(`DROP TABLE \`KANBANS\``);
    await queryRunner.query(`DROP TABLE \`SWIMLANES\``);
    await queryRunner.query(`DROP TABLE \`COLABORADORES\``);
    await queryRunner.query(`DROP TABLE \`COMENTARIOS\``);
    await queryRunner.query(`DROP TABLE \`CASOS_DE_TESTE\``);
    await queryRunner.query(`DROP TABLE \`EXECUCOES_DE_TESTE\``);
    await queryRunner.query(`DROP TABLE \`CASOS_DE_USO\``);
    await queryRunner.query(`DROP TABLE \`REQUISITOS_FUNCIONAIS\``);
    await queryRunner.query(`DROP TABLE \`RESULTADO_REQUISITOS\``);
    await queryRunner.query(`DROP TABLE \`PRIORIZACAO_STAKEHOLDERS\``);
    await queryRunner.query(`DROP TABLE \`STAKEHOLDERS\``);
    await queryRunner.query(`DROP TABLE \`PROJETOS\``);
    await queryRunner.query(`DROP TABLE \`SUITES_DE_TESTE\``);
    await queryRunner.query(`DROP TABLE \`SPRINTS\``);
    await queryRunner.query(`DROP TABLE \`FATORES_TECNICOS_PROJETOS\``);
    await queryRunner.query(`DROP TABLE \`FATORES_TECNICOS\``);
    await queryRunner.query(`DROP TABLE \`FATORES_AMBIENTAIS_PROJETOS\``);
    await queryRunner.query(`DROP TABLE \`FATORES_AMBIENTAIS\``);
    await queryRunner.query(`DROP TABLE \`ESTIMATIVAS_ESFORCOS\``);
    await queryRunner.query(`DROP TABLE \`COLABORADORES_PROJETOS\``);
    await queryRunner.query(`DROP TABLE \`USUARIOS\``);
    await queryRunner.query(`DROP TABLE \`STATUS_PRIORIZACAO\``);
    await queryRunner.query(`DROP TABLE \`ATORES\``);
    await queryRunner.query(`DROP TABLE \`CENARIOS\``);
    await queryRunner.query(`DROP TABLE \`ARQUIVOS\``);
  }
}
