import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddSeleniumIntegration1765845820860 implements MigrationInterface {
  name = 'AddSeleniumIntegration1765845820860';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`ACOES_DE_TESTE\` (\`ACT_ID\` int NOT NULL AUTO_INCREMENT, \`ACT_ORDEM\` int NOT NULL, \`ACT_TIPO\` enum ('NAVEGAR', 'CLICAR', 'DIGITAR', 'SELECIONAR', 'ESPERAR', 'VALIDAR_TEXTO', 'VALIDAR_ELEMENTO', 'SCREENSHOT', 'EXECUTAR_SCRIPT', 'SCROLL', 'HOVER', 'DUPLO_CLIQUE', 'CLICAR_DIREITO', 'LIMPAR_CAMPO', 'PRESSIONAR_TECLA', 'UPLOAD_ARQUIVO', 'TROCAR_JANELA', 'TROCAR_FRAME', 'ACEITAR_ALERTA', 'REJEITAR_ALERTA', 'OBTER_TEXTO_ALERTA') NOT NULL, \`ACT_SELETOR\` varchar(255) NULL, \`ACT_TIPO_SELETOR\` enum ('ID', 'CLASS', 'CSS', 'XPATH', 'NAME', 'TAG', 'LINK_TEXT') NULL, \`ACT_VALOR\` varchar(500) NULL, \`ACT_TIMEOUT\` int NOT NULL DEFAULT '5000', \`ACT_DESCRICAO\` varchar(255) NULL, \`ACT_OBRIGATORIO\` tinyint NOT NULL DEFAULT 1, \`ACT_MENSAGEM_ERRO\` varchar(255) NULL, \`ACT_DATA_CRIACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ACT_DATA_ATUALIZACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`ACT_DATA_EXCLUSAO\` datetime(6) NULL, \`FK_CASO_DE_TESTE_CDT_ID\` int NULL, PRIMARY KEY (\`ACT_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `CREATE TABLE \`CONFIGURACOES_SELENIUM\` (\`CFS_ID\` int NOT NULL AUTO_INCREMENT, \`CFS_NOME\` varchar(100) NOT NULL, \`CFS_NAVEGADOR\` enum ('CHROME', 'FIREFOX', 'EDGE', 'SAFARI') NOT NULL DEFAULT 'CHROME', \`CFS_HEADLESS\` tinyint NOT NULL DEFAULT 0, \`CFS_TIMEOUT_PADRAO\` int NOT NULL DEFAULT '30000', \`CFS_TIMEOUT_IMPLICITO\` int NOT NULL DEFAULT '10000', \`CFS_TIMEOUT_CARREGAMENTO_PAGINA\` int NOT NULL DEFAULT '60000', \`CFS_RESOLUCAO\` varchar(20) NOT NULL DEFAULT '1920x1080', \`CFS_MAXIMIZAR_JANELA\` tinyint NOT NULL DEFAULT 1, \`CFS_ACEITAR_CERTIFICADOS_SSL\` tinyint NOT NULL DEFAULT 1, \`CFS_CAPTURAR_SCREENSHOTS\` tinyint NOT NULL DEFAULT 1, \`CFS_CAPTURAR_LOGS\` tinyint NOT NULL DEFAULT 1, \`CFS_URL_SELENIUM_GRID\` varchar(255) NULL, \`CFS_OPCOES_ADICIONAIS\` json NULL, \`CFS_USER_AGENT\` varchar(255) NULL, \`CFS_PROXY\` varchar(255) NULL, \`CFS_ATIVA\` tinyint NOT NULL DEFAULT 1, \`CFS_DATA_CRIACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`CFS_DATA_ATUALIZACAO\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`CFS_DATA_EXCLUSAO\` datetime(6) NULL, \`FK_PROJETO_PRJ_ID\` int NULL, PRIMARY KEY (\`CFS_ID\`)) ENGINE=InnoDB`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_COR\` \`SWI_COR\` varchar(7) NOT NULL DEFAULT '#6d28d9'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_COR\` \`SWI_COR\` varchar(7) NOT NULL DEFAULT '#6d28d9'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` ADD CONSTRAINT \`FK_8c4df13eb0cdf78a215ce7ad653\` FOREIGN KEY (\`FK_CASO_DE_TESTE_CDT_ID\`) REFERENCES \`CASOS_DE_TESTE\`(\`CDT_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CONFIGURACOES_SELENIUM\` ADD CONSTRAINT \`FK_cca5b6cc79cec3f5ab58f4d938d\` FOREIGN KEY (\`FK_PROJETO_PRJ_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`CONFIGURACOES_SELENIUM\` DROP FOREIGN KEY \`FK_cca5b6cc79cec3f5ab58f4d938d\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` DROP FOREIGN KEY \`FK_8c4df13eb0cdf78a215ce7ad653\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_COR\` \`SWI_COR\` varchar(7) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_COR\` \`SWI_COR\` varchar(7) NOT NULL`,
    );
    await queryRunner.query(`DROP TABLE \`CONFIGURACOES_SELENIUM\``);
    await queryRunner.query(`DROP TABLE \`ACOES_DE_TESTE\``);
  }
}
