import { MigrationInterface, QueryRunner } from 'typeorm';

export class AddManualStepsToAcaoDeTeste1767580699094 implements MigrationInterface {
  name = 'AddManualStepsToAcaoDeTeste1767580699094';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`CENARIOS\` DROP FOREIGN KEY \`FK_A680E32F58A0D62135D90EC600B\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ATORES\` DROP FOREIGN KEY \`FK_B3DDC2A92CAA7C6D1386A1C378B\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ESTIMATIVAS_ESFORCOS\` DROP FOREIGN KEY \`FK_D8A1435775F634E45757FECC3D5\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` DROP FOREIGN KEY \`FK_33547206E5E9D4AEEBBE967B604\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` DROP FOREIGN KEY \`FK_831BB9A8AB96127713017B69A29\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` DROP FOREIGN KEY \`FK_41F07677E6F8179942791B2C299\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` DROP FOREIGN KEY \`FK_6F81EC50A173807E18B6C813777\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` DROP FOREIGN KEY \`FK_58AAF08431B217DC3845C78DA5F\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`KANBANS\` DROP FOREIGN KEY \`FK_7B35D1DF7F716FF30C825CE9897\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` DROP FOREIGN KEY \`FK_B4640DA6FEB4E19EFFBF3E6DF9E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` DROP FOREIGN KEY \`FK_1B34F167EB645F5ED4C44D9444E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` DROP FOREIGN KEY \`FK_344F8118376D5A82E4ECB4D4923\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_009516F3B82AF76B34016A8AF11\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_28A13D2B8B6E2907E9F73B0812E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_48311CE7E29574D5CBE2E57DE23\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_6108264AC009132260079873F8C\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_F67D042A43CA9187F6FFBBA1BBD\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` DROP FOREIGN KEY \`FK_9CBCD836FC4F159AC7E7CA68137\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` DROP FOREIGN KEY \`FK_B6277B122D6885971D6DFD0AD95\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_4E3922310803560CBA80659F279\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_FB7231B4EB38AC98B4BE32C3C7B\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` DROP FOREIGN KEY \`FK_3733A295E8F3C4E6F23F3BABC2E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` DROP FOREIGN KEY \`FK_62BC9443115B976B578B5E37DC0\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_18C191A2937D73B149EB6F86597\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_2672110843A47157079202A5CF7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_26F5CBA11CC26D82765CC57EAFE\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`RESULTADO_REQUISITOS\` DROP FOREIGN KEY \`FK_8B08CF83FFD1E3F815C8B45B6FE\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`REQUISITOS_FUNCIONAIS\` DROP FOREIGN KEY \`FK_1670334E6CB5E4A12AE45517CC7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_USO\` DROP FOREIGN KEY \`FK_0ECBAA9A062F7A4FBFDD15C9902\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`EXECUCOES_DE_TESTE\` DROP FOREIGN KEY \`FK_8814CAE507F613801943E0D7F6C\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_A4806D23A33189C705EEC34FFAC\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_B4366658430072A75E6767EC866\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_BB77D73B65984173FDAD8081EA8\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_C605514B9A8B8C7D1F0368AB195\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES\` DROP FOREIGN KEY \`FK_65A1F543DDC8B9A47B0E403CAA6\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_21D329DC2438A0D5CE536A3D356\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_671BAB7EC79797879138366A686\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_A2F3842C6D1E9DA85BE63795669\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_26cd79afda4520bec237e087870\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_4f7d77d53ee1ab76304349fc33c\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_642d786872565727dab940db73e\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_8a231b70354ac2acc0e43fb41c7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` DROP FOREIGN KEY \`FK_17071DA5D078578DC872197749C\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` DROP FOREIGN KEY \`FK_F8A81B2401C309E707D8762768E\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` DROP FOREIGN KEY \`FK_3500F15E563669A9D11DB7FA376\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` DROP FOREIGN KEY \`FK_848E3ADAA61749CE5F871992906\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` DROP FOREIGN KEY \`FK_A914F1497FDC7F03AC8A40AF0A1\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` DROP FOREIGN KEY \`FK_B878609198E33979B5CAB651694\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` DROP FOREIGN KEY \`FK_0A663735B1C11C6DFA3EAD92B9D\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` DROP FOREIGN KEY \`FK_7A69302BC35BF787FD17EA067F9\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_f8a81b2401c309e707d8762768\` ON \`USER_STORY_ARQUIVOS\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` CHANGE \`aRQUIVOSArqId\` \`aRQUIVOSARQID\` int NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` ADD \`ACT_EXECUCAO_TIPO\` enum ('MANUAL', 'AUTOMATIZADO') NOT NULL DEFAULT 'AUTOMATIZADO'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` ADD \`ACT_INSTRUCAO_MANUAL\` text NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` ADD \`ACT_RESULTADO_MANUAL\` text NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` CHANGE \`ACT_TIPO\` \`ACT_TIPO\` enum ('NAVEGAR', 'CLICAR', 'DIGITAR', 'SELECIONAR', 'ESPERAR', 'VALIDAR_TEXTO', 'VALIDAR_ELEMENTO', 'SCREENSHOT', 'EXECUTAR_SCRIPT', 'SCROLL', 'HOVER', 'DUPLO_CLIQUE', 'CLICAR_DIREITO', 'LIMPAR_CAMPO', 'PRESSIONAR_TECLA', 'UPLOAD_ARQUIVO', 'TROCAR_JANELA', 'TROCAR_FRAME', 'ACEITAR_ALERTA', 'REJEITAR_ALERTA', 'OBTER_TEXTO_ALERTA', 'PASSO_MANUAL') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint(1) NOT NULL DEFAULT '0'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint(1) NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` CHANGE \`ACT_TIPO\` \`ACT_TIPO\` enum ('NAVEGAR', 'CLICAR', 'DIGITAR', 'SELECIONAR', 'ESPERAR', 'VALIDAR_TEXTO', 'VALIDAR_ELEMENTO', 'SCREENSHOT', 'EXECUTAR_SCRIPT', 'SCROLL', 'HOVER', 'DUPLO_CLIQUE', 'CLICAR_DIREITO', 'LIMPAR_CAMPO', 'PRESSIONAR_TECLA', 'UPLOAD_ARQUIVO', 'TROCAR_JANELA', 'TROCAR_FRAME', 'ACEITAR_ALERTA', 'REJEITAR_ALERTA', 'OBTER_TEXTO_ALERTA', 'PASSO_MANUAL') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint(1) NOT NULL DEFAULT '0'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint(1) NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX \`IDX_756c39c88e3a34d6badafa4fd7\` ON \`USER_STORY_ARQUIVOS\` (\`aRQUIVOSARQID\`)`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CENARIOS\` ADD CONSTRAINT \`FK_a680e32f58a0d62135d90ec600b\` FOREIGN KEY (\`FK_CASOS_DE_USO_CAS_ID\`) REFERENCES \`CASOS_DE_USO\`(\`CAS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ATORES\` ADD CONSTRAINT \`FK_b3ddc2a92caa7c6d1386a1c378b\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ESTIMATIVAS_ESFORCOS\` ADD CONSTRAINT \`FK_d8a1435775f634e45757fecc3d5\` FOREIGN KEY (\`projetoId\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` ADD CONSTRAINT \`FK_33547206e5e9d4aeebbe967b604\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` ADD CONSTRAINT \`FK_831bb9a8ab96127713017b69a29\` FOREIGN KEY (\`FK_FATORES_AMBIENTAIS_AMB_ID\`) REFERENCES \`FATORES_AMBIENTAIS\`(\`AMB_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` ADD CONSTRAINT \`FK_41f07677e6f8179942791b2c299\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` ADD CONSTRAINT \`FK_6f81ec50a173807e18b6c813777\` FOREIGN KEY (\`FK_FATORES_TECNICOS_TEC_ID\`) REFERENCES \`FATORES_TECNICOS\`(\`TEC_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` ADD CONSTRAINT \`FK_58aaf08431b217dc3845c78da5f\` FOREIGN KEY (\`FK_KAN_ID\`) REFERENCES \`KANBANS\`(\`KAN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`KANBANS\` ADD CONSTRAINT \`FK_7b35d1df7f716ff30c825ce9897\` FOREIGN KEY (\`FK_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` ADD CONSTRAINT \`FK_b4640da6feb4e19effbf3e6df9e\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` ADD CONSTRAINT \`FK_34d7b8ac48e9998241edd2df669\` FOREIGN KEY (\`FK_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` ADD CONSTRAINT \`FK_0a045ce99c440dc786063ed6302\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_48311ce7e29574d5cbe2e57de23\` FOREIGN KEY (\`FK_COLABORADOR_COL_CRI_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_28a13d2b8b6e2907e9f73b0812e\` FOREIGN KEY (\`FK_COLABORADOR_COL_RES_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_6108264ac009132260079873f8c\` FOREIGN KEY (\`FK_KANBAN_ID\`) REFERENCES \`KANBANS\`(\`KAN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_009516f3b82af76b34016a8af11\` FOREIGN KEY (\`FK_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_f67d042a43ca9187f6ffbba1bbd\` FOREIGN KEY (\`FK_SWI_ID\`) REFERENCES \`SWIMLANES\`(\`SWI_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` ADD CONSTRAINT \`FK_9cbcd836fc4f159ac7e7ca68137\` FOREIGN KEY (\`FK_SUITE_DE_TESTE_SDT_ID\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` ADD CONSTRAINT \`FK_b6277b122d6885971d6dfd0ad95\` FOREIGN KEY (\`FK_PROJETO_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_4e3922310803560cba80659f279\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_fb7231b4eb38ac98b4be32c3c7b\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` ADD CONSTRAINT \`FK_3733a295e8f3c4e6f23f3babc2e\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` ADD CONSTRAINT \`FK_62bc9443115b976b578b5e37dc0\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_2672110843a47157079202a5cf7\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_18c191a2937d73b149eb6f86597\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_26f5cba11cc26d82765cc57eafe\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`RESULTADO_REQUISITOS\` ADD CONSTRAINT \`FK_8b08cf83ffd1e3f815c8b45b6fe\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`REQUISITOS_FUNCIONAIS\` ADD CONSTRAINT \`FK_1670334e6cb5e4a12ae45517cc7\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_USO\` ADD CONSTRAINT \`FK_0ecbaa9a062f7a4fbfdd15c9902\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`EXECUCOES_DE_TESTE\` ADD CONSTRAINT \`FK_8814cae507f613801943e0d7f6c\` FOREIGN KEY (\`FK_CASO_DE_TESTE_CDT_ID\`) REFERENCES \`CASOS_DE_TESTE\`(\`CDT_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_b4366658430072a75e6767ec866\` FOREIGN KEY (\`FK_CASOS_DE_USO_CAS_ID\`) REFERENCES \`CASOS_DE_USO\`(\`CAS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_bb77d73b65984173fdad8081ea8\` FOREIGN KEY (\`FK_SUITE_DE_TESTE_SDT_ID\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_c605514b9a8b8c7d1f0368ab195\` FOREIGN KEY (\`FK_COLABORADORES_COL_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_a4806d23a33189c705eec34ffac\` FOREIGN KEY (\`FK_PROJETO_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES\` ADD CONSTRAINT \`FK_65a1f543ddc8b9a47b0e403caa6\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_a2f3842c6d1e9da85be63795669\` FOREIGN KEY (\`FK_COLABORADORES_COL_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_671bab7ec79797879138366a686\` FOREIGN KEY (\`FK_COLABORADORES_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_21d329dc2438a0d5ce536a3d356\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_9115642dafccabbd120e64cb2af\` FOREIGN KEY (\`FK_DESTINATARIO_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_f8f774153aa6a36467ed7706124\` FOREIGN KEY (\`FK_REMETENTE_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_279ab0017c58aeafb611271fd4d\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_bdc26e5b5b398a73569c6f5daf4\` FOREIGN KEY (\`FK_COMENTARIO\`) REFERENCES \`COMENTARIOS\`(\`CMN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` ADD CONSTRAINT \`FK_17071da5d078578dc872197749c\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` ADD CONSTRAINT \`FK_756c39c88e3a34d6badafa4fd73\` FOREIGN KEY (\`aRQUIVOSARQID\`) REFERENCES \`ARQUIVOS\`(\`ARQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` ADD CONSTRAINT \`FK_3500f15e563669a9d11db7fa376\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` ADD CONSTRAINT \`FK_848e3adaa61749ce5f871992906\` FOREIGN KEY (\`cOLABORADORESCOLID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` ADD CONSTRAINT \`FK_a914f1497fdc7f03ac8a40af0a1\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` ADD CONSTRAINT \`FK_b878609198e33979b5cab651694\` FOREIGN KEY (\`sPRINTSSPRID\`) REFERENCES \`SPRINTS\`(\`SPR_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` ADD CONSTRAINT \`FK_7a69302bc35bf787fd17ea067f9\` FOREIGN KEY (\`id_ancestor\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` ADD CONSTRAINT \`FK_0a663735b1c11c6dfa3ead92b9d\` FOREIGN KEY (\`id_descendant\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` DROP FOREIGN KEY \`FK_0a663735b1c11c6dfa3ead92b9d\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` DROP FOREIGN KEY \`FK_7a69302bc35bf787fd17ea067f9\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` DROP FOREIGN KEY \`FK_b878609198e33979b5cab651694\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` DROP FOREIGN KEY \`FK_a914f1497fdc7f03ac8a40af0a1\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` DROP FOREIGN KEY \`FK_848e3adaa61749ce5f871992906\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` DROP FOREIGN KEY \`FK_3500f15e563669a9d11db7fa376\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` DROP FOREIGN KEY \`FK_756c39c88e3a34d6badafa4fd73\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` DROP FOREIGN KEY \`FK_17071da5d078578dc872197749c\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_bdc26e5b5b398a73569c6f5daf4\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_279ab0017c58aeafb611271fd4d\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_f8f774153aa6a36467ed7706124\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` DROP FOREIGN KEY \`FK_9115642dafccabbd120e64cb2af\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_21d329dc2438a0d5ce536a3d356\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_671bab7ec79797879138366a686\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` DROP FOREIGN KEY \`FK_a2f3842c6d1e9da85be63795669\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES\` DROP FOREIGN KEY \`FK_65a1f543ddc8b9a47b0e403caa6\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_a4806d23a33189c705eec34ffac\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_c605514b9a8b8c7d1f0368ab195\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_bb77d73b65984173fdad8081ea8\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` DROP FOREIGN KEY \`FK_b4366658430072a75e6767ec866\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`EXECUCOES_DE_TESTE\` DROP FOREIGN KEY \`FK_8814cae507f613801943e0d7f6c\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_USO\` DROP FOREIGN KEY \`FK_0ecbaa9a062f7a4fbfdd15c9902\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`REQUISITOS_FUNCIONAIS\` DROP FOREIGN KEY \`FK_1670334e6cb5e4a12ae45517cc7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`RESULTADO_REQUISITOS\` DROP FOREIGN KEY \`FK_8b08cf83ffd1e3f815c8b45b6fe\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_26f5cba11cc26d82765cc57eafe\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_18c191a2937d73b149eb6f86597\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_2672110843a47157079202a5cf7\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` DROP FOREIGN KEY \`FK_62bc9443115b976b578b5e37dc0\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` DROP FOREIGN KEY \`FK_3733a295e8f3c4e6f23f3babc2e\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_fb7231b4eb38ac98b4be32c3c7b\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_4e3922310803560cba80659f279\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` DROP FOREIGN KEY \`FK_b6277b122d6885971d6dfd0ad95\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` DROP FOREIGN KEY \`FK_9cbcd836fc4f159ac7e7ca68137\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_f67d042a43ca9187f6ffbba1bbd\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_009516f3b82af76b34016a8af11\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_6108264ac009132260079873f8c\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_28a13d2b8b6e2907e9f73b0812e\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` DROP FOREIGN KEY \`FK_48311ce7e29574d5cbe2e57de23\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` DROP FOREIGN KEY \`FK_0a045ce99c440dc786063ed6302\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` DROP FOREIGN KEY \`FK_34d7b8ac48e9998241edd2df669\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` DROP FOREIGN KEY \`FK_b4640da6feb4e19effbf3e6df9e\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`KANBANS\` DROP FOREIGN KEY \`FK_7b35d1df7f716ff30c825ce9897\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` DROP FOREIGN KEY \`FK_58aaf08431b217dc3845c78da5f\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` DROP FOREIGN KEY \`FK_6f81ec50a173807e18b6c813777\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` DROP FOREIGN KEY \`FK_41f07677e6f8179942791b2c299\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` DROP FOREIGN KEY \`FK_831bb9a8ab96127713017b69a29\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` DROP FOREIGN KEY \`FK_33547206e5e9d4aeebbe967b604\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ESTIMATIVAS_ESFORCOS\` DROP FOREIGN KEY \`FK_d8a1435775f634e45757fecc3d5\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ATORES\` DROP FOREIGN KEY \`FK_b3ddc2a92caa7c6d1386a1c378b\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`CENARIOS\` DROP FOREIGN KEY \`FK_a680e32f58a0d62135d90ec600b\``,
    );
    await queryRunner.query(
      `DROP INDEX \`IDX_756c39c88e3a34d6badafa4fd7\` ON \`USER_STORY_ARQUIVOS\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint NOT NULL DEFAULT '0'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` CHANGE \`ACT_TIPO\` \`ACT_TIPO\` enum ('NAVEGAR', 'CLICAR', 'DIGITAR', 'SELECIONAR', 'ESPERAR', 'VALIDAR_TEXTO', 'VALIDAR_ELEMENTO', 'SCREENSHOT', 'EXECUTAR_SCRIPT', 'SCROLL', 'HOVER', 'DUPLO_CLIQUE', 'CLICAR_DIREITO', 'LIMPAR_CAMPO', 'PRESSIONAR_TECLA', 'UPLOAD_ARQUIVO', 'TROCAR_JANELA', 'TROCAR_FRAME', 'ACEITAR_ALERTA', 'REJEITAR_ALERTA', 'OBTER_TEXTO_ALERTA') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint NOT NULL DEFAULT '0'`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` CHANGE \`ACT_TIPO\` \`ACT_TIPO\` enum ('NAVEGAR', 'CLICAR', 'DIGITAR', 'SELECIONAR', 'ESPERAR', 'VALIDAR_TEXTO', 'VALIDAR_ELEMENTO', 'SCREENSHOT', 'EXECUTAR_SCRIPT', 'SCROLL', 'HOVER', 'DUPLO_CLIQUE', 'CLICAR_DIREITO', 'LIMPAR_CAMPO', 'PRESSIONAR_TECLA', 'UPLOAD_ARQUIVO', 'TROCAR_JANELA', 'TROCAR_FRAME', 'ACEITAR_ALERTA', 'REJEITAR_ALERTA', 'OBTER_TEXTO_ALERTA') NOT NULL`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` DROP COLUMN \`ACT_RESULTADO_MANUAL\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` DROP COLUMN \`ACT_INSTRUCAO_MANUAL\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`ACOES_DE_TESTE\` DROP COLUMN \`ACT_EXECUCAO_TIPO\``,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` CHANGE \`aRQUIVOSARQID\` \`aRQUIVOSArqId\` int NOT NULL`,
    );
    await queryRunner.query(
      `CREATE INDEX \`IDX_f8a81b2401c309e707d8762768\` ON \`USER_STORY_ARQUIVOS\` (\`aRQUIVOSArqId\`)`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` ADD CONSTRAINT \`FK_7A69302BC35BF787FD17EA067F9\` FOREIGN KEY (\`id_ancestor\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE_RELATION_closure\` ADD CONSTRAINT \`FK_0A663735B1C11C6DFA3EAD92B9D\` FOREIGN KEY (\`id_descendant\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` ADD CONSTRAINT \`FK_B878609198E33979B5CAB651694\` FOREIGN KEY (\`sPRINTSSPRID\`) REFERENCES \`SPRINTS\`(\`SPR_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SPRINTS_USERS_STORIES\` ADD CONSTRAINT \`FK_A914F1497FDC7F03AC8A40AF0A1\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` ADD CONSTRAINT \`FK_848E3ADAA61749CE5F871992906\` FOREIGN KEY (\`cOLABORADORESCOLID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES_COLABORADORES\` ADD CONSTRAINT \`FK_3500F15E563669A9D11DB7FA376\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` ADD CONSTRAINT \`FK_F8A81B2401C309E707D8762768E\` FOREIGN KEY (\`aRQUIVOSArqId\`) REFERENCES \`ARQUIVOS\`(\`ARQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORY_ARQUIVOS\` ADD CONSTRAINT \`FK_17071DA5D078578DC872197749C\` FOREIGN KEY (\`uSERSTORIESUSTID\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE CASCADE ON UPDATE CASCADE`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_8a231b70354ac2acc0e43fb41c7\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_642d786872565727dab940db73e\` FOREIGN KEY (\`FK_DESTINATARIO_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_4f7d77d53ee1ab76304349fc33c\` FOREIGN KEY (\`FK_COMENTARIO\`) REFERENCES \`COMENTARIOS\`(\`CMN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`NOTIFICACOES\` ADD CONSTRAINT \`FK_26cd79afda4520bec237e087870\` FOREIGN KEY (\`FK_REMETENTE_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_A2F3842C6D1E9DA85BE63795669\` FOREIGN KEY (\`FK_COLABORADORES_COL_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_671BAB7EC79797879138366A686\` FOREIGN KEY (\`FK_COLABORADORES_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES_PROJETOS\` ADD CONSTRAINT \`FK_21D329DC2438A0D5CE536A3D356\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COLABORADORES\` ADD CONSTRAINT \`FK_65A1F543DDC8B9A47B0E403CAA6\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_C605514B9A8B8C7D1F0368AB195\` FOREIGN KEY (\`FK_COLABORADORES_COL_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_BB77D73B65984173FDAD8081EA8\` FOREIGN KEY (\`FK_SUITE_DE_TESTE_SDT_ID\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_B4366658430072A75E6767EC866\` FOREIGN KEY (\`FK_CASOS_DE_USO_CAS_ID\`) REFERENCES \`CASOS_DE_USO\`(\`CAS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_TESTE\` ADD CONSTRAINT \`FK_A4806D23A33189C705EEC34FFAC\` FOREIGN KEY (\`FK_PROJETO_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`EXECUCOES_DE_TESTE\` ADD CONSTRAINT \`FK_8814CAE507F613801943E0D7F6C\` FOREIGN KEY (\`FK_CASO_DE_TESTE_CDT_ID\`) REFERENCES \`CASOS_DE_TESTE\`(\`CDT_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CASOS_DE_USO\` ADD CONSTRAINT \`FK_0ECBAA9A062F7A4FBFDD15C9902\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`REQUISITOS_FUNCIONAIS\` ADD CONSTRAINT \`FK_1670334E6CB5E4A12AE45517CC7\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`RESULTADO_REQUISITOS\` ADD CONSTRAINT \`FK_8B08CF83FFD1E3F815C8B45B6FE\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_26F5CBA11CC26D82765CC57EAFE\` FOREIGN KEY (\`FK_REQUISITOS_FUNCIONAIS_REQ_ID\`) REFERENCES \`REQUISITOS_FUNCIONAIS\`(\`REQ_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_2672110843A47157079202A5CF7\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_18C191A2937D73B149EB6F86597\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` ADD CONSTRAINT \`FK_62BC9443115B976B578B5E37DC0\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STAKEHOLDERS\` ADD CONSTRAINT \`FK_3733A295E8F3C4E6F23F3BABC2E\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_FB7231B4EB38AC98B4BE32C3C7B\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_4E3922310803560CBA80659F279\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` ADD CONSTRAINT \`FK_B6277B122D6885971D6DFD0AD95\` FOREIGN KEY (\`FK_PROJETO_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUITES_DE_TESTE\` ADD CONSTRAINT \`FK_9CBCD836FC4F159AC7E7CA68137\` FOREIGN KEY (\`FK_SUITE_DE_TESTE_SDT_ID\`) REFERENCES \`SUITES_DE_TESTE\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_F67D042A43CA9187F6FFBBA1BBD\` FOREIGN KEY (\`FK_SWI_ID\`) REFERENCES \`SWIMLANES\`(\`SWI_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_6108264AC009132260079873F8C\` FOREIGN KEY (\`FK_KANBAN_ID\`) REFERENCES \`KANBANS\`(\`KAN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_48311CE7E29574D5CBE2E57DE23\` FOREIGN KEY (\`FK_COLABORADOR_COL_CRI_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_28A13D2B8B6E2907E9F73B0812E\` FOREIGN KEY (\`FK_COLABORADOR_COL_RES_ID\`) REFERENCES \`COLABORADORES\`(\`COL_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`USER_STORIES\` ADD CONSTRAINT \`FK_009516F3B82AF76B34016A8AF11\` FOREIGN KEY (\`FK_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` ADD CONSTRAINT \`FK_344F8118376D5A82E4ECB4D4923\` FOREIGN KEY (\`FK_USUARIO_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`COMENTARIOS\` ADD CONSTRAINT \`FK_1B34F167EB645F5ED4C44D9444E\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SUBTAREFAS\` ADD CONSTRAINT \`FK_B4640DA6FEB4E19EFFBF3E6DF9E\` FOREIGN KEY (\`FK_USER_STORY\`) REFERENCES \`USER_STORIES\`(\`UST_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`KANBANS\` ADD CONSTRAINT \`FK_7B35D1DF7F716FF30C825CE9897\` FOREIGN KEY (\`FK_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`SWIMLANES\` ADD CONSTRAINT \`FK_58AAF08431B217DC3845C78DA5F\` FOREIGN KEY (\`FK_KAN_ID\`) REFERENCES \`KANBANS\`(\`KAN_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` ADD CONSTRAINT \`FK_6F81EC50A173807E18B6C813777\` FOREIGN KEY (\`FK_FATORES_TECNICOS_TEC_ID\`) REFERENCES \`FATORES_TECNICOS\`(\`TEC_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_TECNICOS_PROJETOS\` ADD CONSTRAINT \`FK_41F07677E6F8179942791B2C299\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` ADD CONSTRAINT \`FK_831BB9A8AB96127713017B69A29\` FOREIGN KEY (\`FK_FATORES_AMBIENTAIS_AMB_ID\`) REFERENCES \`FATORES_AMBIENTAIS\`(\`AMB_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`FATORES_AMBIENTAIS_PROJETOS\` ADD CONSTRAINT \`FK_33547206E5E9D4AEEBBE967B604\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ESTIMATIVAS_ESFORCOS\` ADD CONSTRAINT \`FK_D8A1435775F634E45757FECC3D5\` FOREIGN KEY (\`projetoId\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`ATORES\` ADD CONSTRAINT \`FK_B3DDC2A92CAA7C6D1386A1C378B\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`CENARIOS\` ADD CONSTRAINT \`FK_A680E32F58A0D62135D90EC600B\` FOREIGN KEY (\`FK_CASOS_DE_USO_CAS_ID\`) REFERENCES \`CASOS_DE_USO\`(\`CAS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
  }
}
