import { MigrationInterface, QueryRunner } from "typeorm";

export class AddProjetoToStatusPriorizacao1768867478896 implements MigrationInterface {
    name = 'AddProjetoToStatusPriorizacao1768867478896'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_4e3922310803560cba80659f279\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_fb7231b4eb38ac98b4be32c3c7b\``);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_18c191a2937d73b149eb6f86597\``);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_2672110843a47157079202a5cf7\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP COLUMN \`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP COLUMN \`FK_STAKEHOLDERS_STA_ID\``);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP COLUMN \`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\``);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP COLUMN \`FK_STAKEHOLDERS_STA_ID\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD \`FK_USUARIOS_USU_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD \`FK_PROJETOS_PRO_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD \`FK_USUARIOS_USU_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_79315719e4897a14f6be25dc27e\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_da3dc6d934ff1fda746308185f2\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_80fe897b9aac68679adfa57de61\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP FOREIGN KEY \`FK_80fe897b9aac68679adfa57de61\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_da3dc6d934ff1fda746308185f2\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP FOREIGN KEY \`FK_79315719e4897a14f6be25dc27e\``);
        await queryRunner.query(`ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` DROP COLUMN \`FK_USUARIOS_USU_ID\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP COLUMN \`FK_PROJETOS_PRO_ID\``);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` DROP COLUMN \`FK_USUARIOS_USU_ID\``);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD \`FK_STAKEHOLDERS_STA_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD \`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD \`FK_STAKEHOLDERS_STA_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD \`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_2672110843a47157079202a5cf7\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`PRIORIZACAO_STAKEHOLDERS\` ADD CONSTRAINT \`FK_18c191a2937d73b149eb6f86597\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_fb7231b4eb38ac98b4be32c3c7b\` FOREIGN KEY (\`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`STATUS_PRIORIZACAO\` ADD CONSTRAINT \`FK_4e3922310803560cba80659f279\` FOREIGN KEY (\`FK_STAKEHOLDERS_STA_ID\`) REFERENCES \`STAKEHOLDERS\`(\`STA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
