import { MigrationInterface, QueryRunner } from "typeorm";

export class AddBillingModule1768772678317 implements MigrationInterface {
    name = 'AddBillingModule1768772678317'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`HISTORICO_PAGAMENTOS\` (\`HPA_ID\` int NOT NULL AUTO_INCREMENT, \`HPA_VALOR\` decimal(10,2) NOT NULL, \`HPA_STATUS\` enum ('PENDENTE', 'APROVADO', 'REJEITADO', 'CANCELADO', 'REEMBOLSADO') NOT NULL DEFAULT 'PENDENTE', \`HPA_METODO\` enum ('CARTAO_CREDITO', 'BOLETO', 'PIX', 'PAYPAL') NOT NULL, \`HPA_DATA_PAGAMENTO\` datetime NOT NULL, \`HPA_DATA_VENCIMENTO\` datetime NOT NULL, \`HPA_TRANSACAO_ID\` varchar(255) NULL, \`HPA_OBSERVACOES\` text NULL, \`HPA_CREATED_AT\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`FK_ASSINATURAS_ASS_ID\` int NOT NULL, PRIMARY KEY (\`HPA_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`ASSINATURAS\` (\`ASS_ID\` int NOT NULL AUTO_INCREMENT, \`ASS_STATUS\` enum ('ATIVA', 'CANCELADA', 'SUSPENSA', 'EXPIRADA', 'TRIAL') NOT NULL DEFAULT 'ATIVA', \`ASS_TIPO_PERIODO\` enum ('MENSAL', 'ANUAL') NOT NULL DEFAULT 'MENSAL', \`ASS_DATA_INICIO\` datetime NOT NULL, \`ASS_DATA_FIM\` datetime NULL, \`ASS_PROXIMO_PAGAMENTO\` datetime NOT NULL, \`ASS_VALOR_ATUAL\` decimal(10,2) NOT NULL, \`ASS_AUTO_RENOVACAO\` tinyint NOT NULL DEFAULT 1, \`ASS_TRIAL\` tinyint NOT NULL DEFAULT 0, \`ASS_DATA_FIM_TRIAL\` datetime NULL, \`ASS_CREATED_AT\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`ASS_UPDATED_AT\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`FK_USUARIOS_USU_ID\` int NOT NULL, \`FK_PLANOS_PLA_ID\` int NOT NULL, \`FK_PROJETOS_PRO_ID\` int NULL, PRIMARY KEY (\`ASS_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`PLANOS\` (\`PLA_ID\` int NOT NULL AUTO_INCREMENT, \`PLA_NOME\` varchar(50) NOT NULL, \`PLA_DESCRICAO\` text NOT NULL, \`PLA_PRECO_MENSAL\` decimal(10,2) NOT NULL, \`PLA_PRECO_ANUAL\` decimal(10,2) NOT NULL, \`PLA_LIMITE_PROJETOS\` int NULL, \`PLA_LIMITE_USUARIOS\` int NULL, \`PLA_FERRAMENTAS_DISPONIVEIS\` text NOT NULL, \`PLA_CARACTERISTICAS\` text NOT NULL, \`PLA_ATIVO\` tinyint NOT NULL DEFAULT 1, \`PLA_CREATED_AT\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`PLA_UPDATED_AT\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_790676a6cfefdb0c58bb9a8ef4\` (\`PLA_NOME\`), PRIMARY KEY (\`PLA_ID\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint(1) NOT NULL DEFAULT '0'`);
        await queryRunner.query(`ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint(1) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTOS\` ADD CONSTRAINT \`FK_122809895ce96b740d08fd72a2a\` FOREIGN KEY (\`FK_ASSINATURAS_ASS_ID\`) REFERENCES \`ASSINATURAS\`(\`ASS_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURAS\` ADD CONSTRAINT \`FK_639875d15cff60950cb9dfae3b1\` FOREIGN KEY (\`FK_USUARIOS_USU_ID\`) REFERENCES \`USUARIOS\`(\`USU_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURAS\` ADD CONSTRAINT \`FK_ae049d213e2ca582c59fb9a7e94\` FOREIGN KEY (\`FK_PLANOS_PLA_ID\`) REFERENCES \`PLANOS\`(\`PLA_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`ASSINATURAS\` ADD CONSTRAINT \`FK_fc6aaf2aa3ee9edd72ef4050d7a\` FOREIGN KEY (\`FK_PROJETOS_PRO_ID\`) REFERENCES \`PROJETOS\`(\`PRO_ID\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`ASSINATURAS\` DROP FOREIGN KEY \`FK_fc6aaf2aa3ee9edd72ef4050d7a\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURAS\` DROP FOREIGN KEY \`FK_ae049d213e2ca582c59fb9a7e94\``);
        await queryRunner.query(`ALTER TABLE \`ASSINATURAS\` DROP FOREIGN KEY \`FK_639875d15cff60950cb9dfae3b1\``);
        await queryRunner.query(`ALTER TABLE \`HISTORICO_PAGAMENTOS\` DROP FOREIGN KEY \`FK_122809895ce96b740d08fd72a2a\``);
        await queryRunner.query(`ALTER TABLE \`SUBTAREFAS\` CHANGE \`SBT_COMPLETADA\` \`SBT_COMPLETADA\` tinyint NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`SWIMLANES\` CHANGE \`SWI_VERTICAL\` \`SWI_VERTICAL\` tinyint NOT NULL DEFAULT '0'`);
        await queryRunner.query(`DROP INDEX \`IDX_790676a6cfefdb0c58bb9a8ef4\` ON \`PLANOS\``);
        await queryRunner.query(`DROP TABLE \`PLANOS\``);
        await queryRunner.query(`DROP TABLE \`ASSINATURAS\``);
        await queryRunner.query(`DROP TABLE \`HISTORICO_PAGAMENTOS\``);
    }

}
