-- Create test database schema for ocus_focus_test

-- Drop the database if it exists and create a new one
DROP DATABASE IF EXISTS ocus_focus_test;
CREATE DATABASE ocus_focus_test;
USE ocus_focus_test;

-- Create tables in order of dependencies (parents first)
CREATE TABLE `USUARIOS` (
    `USU_ID` int NOT NULL AUTO_INCREMENT,
    `USU_DATA_CADASTRO` timestamp(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`USU_ID`)
) ENGINE=InnoDB;

CREATE TABLE `PROJETOS` (
    `PRO_ID` int NOT NULL AUTO_INCREMENT,
    `PRO_NOME` varchar(100) NOT NULL,
    `PRO_DESCRICAO` varchar(255) NOT NULL,
    `PRO_EMPRESA` varchar(50) NOT NULL,
    `PRO_DATA_INICIO` date NOT NULL,
    `PRO_PREVISAO_FIM` date NOT NULL,
    `PRO_STATUS` enum ('EM ANDAMENTO', 'FINALIZADO', 'CANCELADO') NOT NULL DEFAULT 'EM ANDAMENTO',
    `PRO_RESTFACTOR` double(4,2) NULL,
    `PRO_RESEFACTOR` double(4,2) NULL,
    PRIMARY KEY (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `COLABORADORES` (
    `COL_ID` int NOT NULL AUTO_INCREMENT,
    `COL_NOME` varchar(100) NOT NULL,
    `COL_EMAIL` varchar(255) NOT NULL,
    `COL_SENHA` varchar(100) NOT NULL,
    `COL_EMPRESA` varchar(30) NOT NULL,
    `COL_CARGO` enum ('Gerente de Projeto', 'Analista de Sistemas', 'Desenvolvedor', 'Product Owner', 'Scrum Master') NOT NULL DEFAULT 'Desenvolvedor',
    `FK_USUARIOS_USU_ID` int NULL,
    PRIMARY KEY (`COL_ID`),
    FOREIGN KEY (`FK_USUARIOS_USU_ID`) REFERENCES `USUARIOS` (`USU_ID`) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE `COLABORADORES_PROJETOS` (
    `COP_ID` int NOT NULL AUTO_INCREMENT,
    `COP_ATIVO` tinyint NOT NULL,
    `COP_ADMINISTRADOR` tinyint NOT NULL,
    `FK_COLABORADORES_COL_ID` int NULL,
    `FK_COLABORADORES_FK_USUARIOS_USU_ID` int NULL,
    `FK_PROJETOS_PRO_ID` int NULL,
    PRIMARY KEY (`COP_ID`),
    FOREIGN KEY (`FK_COLABORADORES_COL_ID`) REFERENCES `COLABORADORES` (`COL_ID`),
    FOREIGN KEY (`FK_COLABORADORES_FK_USUARIOS_USU_ID`) REFERENCES `USUARIOS` (`USU_ID`),
    FOREIGN KEY (`FK_PROJETOS_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `STAKEHOLDERS` (
    `STA_ID` int NOT NULL AUTO_INCREMENT,
    `STA_CHAVE` varchar(100) NOT NULL,
    `STA_SENHA` varchar(100) NOT NULL,
    `STA_NOME` varchar(100) NOT NULL,
    `STA_CARGO` varchar(50) NOT NULL,
    `STA_EMAIL` varchar(255) NOT NULL,
    `FK_USUARIOS_USU_ID` int NULL,
    `FK_PROJETOS_PRO_ID` int NULL,
    PRIMARY KEY (`STA_ID`),
    FOREIGN KEY (`FK_USUARIOS_USU_ID`) REFERENCES `USUARIOS` (`USU_ID`),
    FOREIGN KEY (`FK_PROJETOS_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `STATUS_PRIORIZACAO` (
    `SPA_ID` int NOT NULL AUTO_INCREMENT,
    `SPA_PARTICIPACAO_REALIZADA` tinyint NOT NULL DEFAULT 0,
    `SPA_ALERTA_EMITIDO` tinyint NOT NULL DEFAULT 0,
    `FK_STAKEHOLDERS_STA_ID` int NULL,
    `FK_STAKEHOLDERS_FK_USUARIOS_USU_ID` int NULL,
    PRIMARY KEY (`SPA_ID`),
    FOREIGN KEY (`FK_STAKEHOLDERS_STA_ID`) REFERENCES `STAKEHOLDERS` (`STA_ID`),
    FOREIGN KEY (`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID`) REFERENCES `USUARIOS` (`USU_ID`)
) ENGINE=InnoDB;

CREATE TABLE `KANBANS` (
    `KAN_ID` int NOT NULL AUTO_INCREMENT,
    `FK_PRO_ID` int NULL,
    PRIMARY KEY (`KAN_ID`),
    UNIQUE INDEX `REL_7b35d1df7f716ff30c825ce989` (`FK_PRO_ID`),
    FOREIGN KEY (`FK_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SWIMLANES` (
    `SWI_ID` int NOT NULL AUTO_INCREMENT,
    `SWI_NOME` varchar(30) NOT NULL,
    `SWI_VERTICAL` tinyint(1) NOT NULL DEFAULT '0',
    `SWI_COR` varchar(7) NOT NULL,
    `SWI_CRIADO_EM` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `SWI_ATUALIZADO_EM` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `FK_KAN_ID` int NULL,
    PRIMARY KEY (`SWI_ID`),
    FOREIGN KEY (`FK_KAN_ID`) REFERENCES `KANBANS` (`KAN_ID`)
) ENGINE=InnoDB;

CREATE TABLE `REQUISITOS_FUNCIONAIS` (
    `REQ_ID` int NOT NULL AUTO_INCREMENT,
    `REQ_ESPECIFICACAO` varchar(1000) NOT NULL,
    `REQ_NOME` varchar(100) NOT NULL,
    `REQ_NUMERO_IDENTIFICADOR` int NOT NULL,
    `FK_PROJETOS_PRO_ID` int NULL,
    PRIMARY KEY (`REQ_ID`),
    FOREIGN KEY (`FK_PROJETOS_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `RESULTADO_REQUISITOS` (
    `RPR_ID` int NOT NULL AUTO_INCREMENT,
    `RPR_RESULTADO_FINAL` enum ('DEVE SER FEITO', 'PERFORMANCE', 'ATRATIVO', 'INDIFERENTE', 'QUESTIONAVEL', 'REVERSO') NOT NULL,
    `FK_REQUISITOS_FUNCIONAIS_REQ_ID` int NULL,
    PRIMARY KEY (`RPR_ID`),
    FOREIGN KEY (`FK_REQUISITOS_FUNCIONAIS_REQ_ID`) REFERENCES `REQUISITOS_FUNCIONAIS` (`REQ_ID`)
) ENGINE=InnoDB;

CREATE TABLE `PRIORIZACAO_STAKEHOLDERS` (
    `PRS_ID` int NOT NULL AUTO_INCREMENT,
    `PRS_CLASSIFICACAO_REQUISITO` enum ('DEVE SER FEITO', 'PERFORMANCE', 'ATRATIVO', 'INDIFERENTE', 'QUESTIONAVEL', 'REVERSO') NOT NULL,
    `PRS_RESPOSTA_POSITIVA` enum ('GOSTARIA', 'ESPERADO', 'NAO IMPORTA', 'CONVIVO COM ISSO', 'NAO GOSTARIA') NOT NULL,
    `PRS_RESPOSTA_NEGATIVA` enum ('GOSTARIA', 'ESPERADO', 'NAO IMPORTA', 'CONVIVO COM ISSO', 'NAO GOSTARIA') NOT NULL,
    `FK_STAKEHOLDERS_STA_ID` int NULL,
    `FK_STAKEHOLDERS_FK_USUARIOS_USU_ID` int NULL,
    `FK_REQUISITOS_FUNCIONAIS_REQ_ID` int NULL,
    PRIMARY KEY (`PRS_ID`),
    FOREIGN KEY (`FK_STAKEHOLDERS_STA_ID`) REFERENCES `STAKEHOLDERS` (`STA_ID`),
    FOREIGN KEY (`FK_STAKEHOLDERS_FK_USUARIOS_USU_ID`) REFERENCES `USUARIOS` (`USU_ID`),
    FOREIGN KEY (`FK_REQUISITOS_FUNCIONAIS_REQ_ID`) REFERENCES `REQUISITOS_FUNCIONAIS` (`REQ_ID`)
) ENGINE=InnoDB;

CREATE TABLE `CASOS_DE_USO` (
    `CAS_ID` int NOT NULL AUTO_INCREMENT,
    `CAS_NOME` varchar(50) NOT NULL,
    `CAS_DESCRICAO` varchar(255) NOT NULL,
    `CAS_COMPLEXIDADE` enum ('SIMPLES', 'MEDIO', 'COMPLEXO') NOT NULL DEFAULT 'SIMPLES',
    `FK_REQUISITOS_FUNCIONAIS_REQ_ID` int NULL,
    PRIMARY KEY (`CAS_ID`),
    FOREIGN KEY (`FK_REQUISITOS_FUNCIONAIS_REQ_ID`) REFERENCES `REQUISITOS_FUNCIONAIS` (`REQ_ID`)
) ENGINE=InnoDB;

CREATE TABLE `CENARIOS` (
    `CEN_ID` int NOT NULL AUTO_INCREMENT,
    `CEN_NOME` varchar(50) NOT NULL,
    `CEN_DESCRICAO` varchar(255) NOT NULL,
    `CEN_TIPO` enum ('PRINCIPAL', 'ALTERNATIVO') NOT NULL DEFAULT 'PRINCIPAL',
    `FK_CASOS_DE_USO_CAS_ID` int NULL,
    PRIMARY KEY (`CEN_ID`),
    FOREIGN KEY (`FK_CASOS_DE_USO_CAS_ID`) REFERENCES `CASOS_DE_USO` (`CAS_ID`)
) ENGINE=InnoDB;

CREATE TABLE `ATORES` (
    `ATO_ID` int NOT NULL AUTO_INCREMENT,
    `ATO_NOME` varchar(30) NOT NULL,
    `ATO_COMPLEXIDADE` enum ('SIMPLES', 'MEDIO', 'COMPLEXO') NOT NULL DEFAULT 'SIMPLES',
    `ATO_DESCRICAO` varchar(255) NOT NULL,
    `FK_PROJETOS_PRO_ID` int NULL,
    PRIMARY KEY (`ATO_ID`),
    FOREIGN KEY (`FK_PROJETOS_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SUITES_DE_TESTE` (
    `id` int NOT NULL AUTO_INCREMENT,
    `SDT_NOME` varchar(50) NOT NULL,
    `SDT_STATUS` enum ('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
    `SDT_DESCRICAO` varchar(255) NOT NULL,
    `SDT_OBSERVACOES` varchar(255) NOT NULL,
    `SDT_DATA_CRIACAO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `SDT_DATA_ATUALIZACAO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `SDT_DATA_EXCLUSAO` datetime(6) NULL,
    `FK_SUITE_DE_TESTE_SDT_ID` int NULL,
    `FK_PROJETO_PRO_ID` int NULL,
    PRIMARY KEY (`id`),
    FOREIGN KEY (`FK_SUITE_DE_TESTE_SDT_ID`) REFERENCES `SUITES_DE_TESTE` (`id`),
    FOREIGN KEY (`FK_PROJETO_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `CASOS_DE_TESTE` (
    `CDT_ID` int NOT NULL AUTO_INCREMENT,
    `CDT_NOME` varchar(50) NOT NULL,
    `CDT_STATUS` enum ('ATIVO', 'INATIVO') NOT NULL DEFAULT 'ATIVO',
    `CDT_METODO` enum ('MANUAL', 'AUTOMATIZADO') NOT NULL DEFAULT 'MANUAL',
    `CDT_TECNICA` enum ('FUNCIONAL', 'ESTRUTURAL') NOT NULL DEFAULT 'FUNCIONAL',
    `CDT_PRIORIDADE` enum ('ALTA', 'MEDIA', 'BAIXA') NOT NULL DEFAULT 'MEDIA',
    `CDT_COMPLEXIDADE` enum ('SIMPLES', 'MEDIO', 'COMPLEXO') NOT NULL DEFAULT 'SIMPLES',
    `CDT_DESCRICAO` varchar(255) NOT NULL,
    `CDT_OBSERVACOES` varchar(255) NOT NULL,
    `CDT_PRE_CONDICAO` varchar(255) NOT NULL,
    `CDT_POS_CONDICAO` varchar(255) NOT NULL,
    `CDT_DADOS_ENTRADA` text NOT NULL,
    `CDT_RESULTADO_ESPERADO` text NOT NULL,
    `CDT_DATA_CRIACAO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `CDT_DATA_ATUALIZACAO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `CDT_DATA_EXCLUSAO` datetime(6) NULL,
    `FK_CASOS_DE_USO_CAS_ID` int NULL,
    `FK_SUITE_DE_TESTE_SDT_ID` int NULL,
    `FK_COLABORADORES_COL_ID` int NULL,
    `FK_PROJETO_PRO_ID` int NULL,
    PRIMARY KEY (`CDT_ID`),
    FOREIGN KEY (`FK_CASOS_DE_USO_CAS_ID`) REFERENCES `CASOS_DE_USO` (`CAS_ID`),
    FOREIGN KEY (`FK_SUITE_DE_TESTE_SDT_ID`) REFERENCES `SUITES_DE_TESTE` (`id`),
    FOREIGN KEY (`FK_COLABORADORES_COL_ID`) REFERENCES `COLABORADORES` (`COL_ID`),
    FOREIGN KEY (`FK_PROJETO_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `EXECUCOES_DE_TESTE` (
    `EDT_ID` int NOT NULL AUTO_INCREMENT,
    `EDT_NOME` varchar(50) NOT NULL,
    `EDT_DATA_EXECUCAO` timestamp NOT NULL,
    `EDT_RESPOSTA` varchar(255) NULL,
    `EDT_RESULTADO` enum ('SUCESSO', 'FALHA', 'PENDENTE') NOT NULL DEFAULT 'PENDENTE',
    `EDT_OBSERVACAO` varchar(255) NULL,
    `EDT_METODO` enum ('MANUAL', 'AUTOMATIZADO') NOT NULL DEFAULT 'MANUAL',
    `EDT_DATA_CRIACAO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `EDT_DATA_ATUALIZACAO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    `EDT_DATA_EXCLUSAO` datetime(6) NULL,
    `FK_CASO_DE_TESTE_CDT_ID` int NULL,
    PRIMARY KEY (`EDT_ID`),
    FOREIGN KEY (`FK_CASO_DE_TESTE_CDT_ID`) REFERENCES `CASOS_DE_TESTE` (`CDT_ID`)
) ENGINE=InnoDB;

CREATE TABLE `USER_STORIES` (
    `UST_ID` int NOT NULL AUTO_INCREMENT,
    `UST_TITULO` varchar(50) NOT NULL,
    `UST_DESCRICAO` varchar(255) NOT NULL,
    `UST_ESTIMATIVA_TEMPO` int NOT NULL,
    `UST_CRIADO_EM` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `UST_MODIFICADO_EM` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `FK_COLABORADOR_COL_CRI_ID` int NULL,
    `FK_COLABORADOR_COL_RES_ID` int NULL,
    `FK_KANBAN_ID` int NULL,
    `FK_PRO_ID` int NULL,
    `FK_SWI_ID` int NULL,
    PRIMARY KEY (`UST_ID`),
    FOREIGN KEY (`FK_COLABORADOR_COL_CRI_ID`) REFERENCES `COLABORADORES` (`COL_ID`),
    FOREIGN KEY (`FK_COLABORADOR_COL_RES_ID`) REFERENCES `COLABORADORES` (`COL_ID`),
    FOREIGN KEY (`FK_KANBAN_ID`) REFERENCES `KANBANS` (`KAN_ID`),
    FOREIGN KEY (`FK_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`),
    FOREIGN KEY (`FK_SWI_ID`) REFERENCES `SWIMLANES` (`SWI_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SUBTAREFAS` (
    `SBT_ID` int NOT NULL AUTO_INCREMENT,
    `SBT_DESCRICAO` varchar(255) NOT NULL,
    `SBT_COMPLETADA` tinyint(1) NOT NULL,
    `FK_USER_STORY` int NULL,
    PRIMARY KEY (`SBT_ID`),
    FOREIGN KEY (`FK_USER_STORY`) REFERENCES `USER_STORIES` (`UST_ID`)
) ENGINE=InnoDB;

CREATE TABLE `COMENTARIOS` (
    `cmn_id` int NOT NULL AUTO_INCREMENT,
    `cmn_comentario` varchar(255) NOT NULL,
    `cmn_criado_em` datetime NOT NULL,
    `cmn_modificado_em` datetime NOT NULL,
    `fk_usuario_id` int NULL,
    `fk_user_story` int NULL,
    PRIMARY KEY (`cmn_id`),
    FOREIGN KEY (`fk_usuario_id`) REFERENCES `USUARIOS` (`USU_ID`),
    FOREIGN KEY (`fk_user_story`) REFERENCES `USER_STORIES` (`UST_ID`)
) ENGINE=InnoDB;

CREATE TABLE `ARQUIVOS` (
    `arq_id` int NOT NULL AUTO_INCREMENT,
    `arq_arquivo` mediumblob NOT NULL,
    PRIMARY KEY (`arq_id`)
) ENGINE=InnoDB;

CREATE TABLE `USER_STORY_ARQUIVOS` (
    `uSERSTORIESUSTID` int NOT NULL,
    `aRQUIVOSArqId` int NOT NULL,
    PRIMARY KEY (`uSERSTORIESUSTID`, `aRQUIVOSArqId`),
    INDEX `IDX_17071da5d078578dc872197749` (`uSERSTORIESUSTID`),
    INDEX `IDX_f8a81b2401c309e707d8762768` (`aRQUIVOSArqId`),
    FOREIGN KEY (`uSERSTORIESUSTID`) REFERENCES `USER_STORIES` (`UST_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`aRQUIVOSArqId`) REFERENCES `ARQUIVOS` (`arq_id`)
) ENGINE=InnoDB;

CREATE TABLE `FATORES_AMBIENTAIS` (
    `AMB_ID` int NOT NULL AUTO_INCREMENT,
    `AMB_DESCRICAO` varchar(255) NOT NULL,
    `AMB_PESO` double(4,2) NOT NULL,
    PRIMARY KEY (`AMB_ID`)
) ENGINE=InnoDB;

CREATE TABLE `FATORES_TECNICOS` (
    `TEC_ID` int NOT NULL AUTO_INCREMENT,
    `TEC_DESCRICAO` varchar(50) NOT NULL,
    `TEC_PESO` double(4,2) NOT NULL,
    PRIMARY KEY (`TEC_ID`)
) ENGINE=InnoDB;

CREATE TABLE `FATORES_AMBIENTAIS_PROJETOS` (
    `AMP_ID` int NOT NULL AUTO_INCREMENT,
    `AMP_VALOR` int NOT NULL,
    `FK_PROJETOS_PRO_ID` int NULL,
    `FK_FATORES_AMBIENTAIS_AMB_ID` int NULL,
    PRIMARY KEY (`AMP_ID`),
    FOREIGN KEY (`FK_PROJETOS_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`),
    FOREIGN KEY (`FK_FATORES_AMBIENTAIS_AMB_ID`) REFERENCES `FATORES_AMBIENTAIS` (`AMB_ID`)
) ENGINE=InnoDB;

CREATE TABLE `FATORES_TECNICOS_PROJETOS` (
    `TEP_ID` int NOT NULL AUTO_INCREMENT,
    `TEP_VALOR` int NOT NULL,
    `FK_PROJETOS_PRO_ID` int NULL,
    `FK_FATORES_TECNICOS_TEC_ID` int NULL,
    PRIMARY KEY (`TEP_ID`),
    FOREIGN KEY (`FK_PROJETOS_PRO_ID`) REFERENCES `PROJETOS` (`PRO_ID`),
    FOREIGN KEY (`FK_FATORES_TECNICOS_TEC_ID`) REFERENCES `FATORES_TECNICOS` (`TEC_ID`)
) ENGINE=InnoDB;

CREATE TABLE `ESTIMATIVAS_ESFORCOS` (
    `EST_ID` int NOT NULL AUTO_INCREMENT,
    `EST_RESULTADO_HORAS` double(8,2) NOT NULL,
    `EST_PESO_ATORES` int NOT NULL,
    `EST_PESO_CASOS_USO` int NOT NULL,
    `EST_PESO_PONTOS_CASOS_USO` int NOT NULL,
    `EST_TFACTOR` double(6,3) NOT NULL,
    `EST_EFACTOR` double(6,3) NOT NULL,
    `EST_RESULTADO_PONTOS_CASOS_USO` double(6,3) NOT NULL,
    `EST_DATA_ESTIMATIVA` varchar(20) NOT NULL,
    `projetoId` int NULL,
    PRIMARY KEY (`EST_ID`),
    FOREIGN KEY (`projetoId`) REFERENCES `PROJETOS` (`PRO_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SPRINTS` (
    `SPR_ID` int NOT NULL AUTO_INCREMENT,
    `SPR_NOME` varchar(30) NOT NULL,
    `SPR_DESCRICAO` varchar(255) NOT NULL,
    `SPR_HORAS_PREVISTAS` int NOT NULL,
    `SPR_DATA_INICIO` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    `SPR_DATA_FIM` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    PRIMARY KEY (`SPR_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SPRINTS_USERS_STORIES` (
    `uSERSTORIESUSTID` int NOT NULL,
    `sPRINTSSPRID` int NOT NULL,
    PRIMARY KEY (`uSERSTORIESUSTID`, `sPRINTSSPRID`),
    INDEX `IDX_a914f1497fdc7f03ac8a40af0a` (`uSERSTORIESUSTID`),
    INDEX `IDX_b878609198e33979b5cab65169` (`sPRINTSSPRID`),
    FOREIGN KEY (`uSERSTORIESUSTID`) REFERENCES `USER_STORIES` (`UST_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`sPRINTSSPRID`) REFERENCES `SPRINTS` (`SPR_ID`)
) ENGINE=InnoDB;

CREATE TABLE `USER_STORIES_COLABORADORES` (
    `uSERSTORIESUSTID` int NOT NULL,
    `cOLABORADORESCOLID` int NOT NULL,
    PRIMARY KEY (`uSERSTORIESUSTID`, `cOLABORADORESCOLID`),
    INDEX `IDX_3500f15e563669a9d11db7fa37` (`uSERSTORIESUSTID`),
    INDEX `IDX_848e3adaa61749ce5f87199290` (`cOLABORADORESCOLID`),
    FOREIGN KEY (`uSERSTORIESUSTID`) REFERENCES `USER_STORIES` (`UST_ID`) ON DELETE CASCADE,
    FOREIGN KEY (`cOLABORADORESCOLID`) REFERENCES `COLABORADORES` (`COL_ID`)
) ENGINE=InnoDB;

CREATE TABLE `TAGS` (
    `tag_id` int NOT NULL AUTO_INCREMENT,
    `tag_nome` varchar(20) NOT NULL,
    `tag_cor` varchar(6) NOT NULL,
    PRIMARY KEY (`tag_id`)
) ENGINE=InnoDB;

CREATE TABLE `SUITES_DE_TESTE_RELATION_closure` (
    `id_ancestor` int NOT NULL,
    `id_descendant` int NOT NULL,
    PRIMARY KEY (`id_ancestor`, `id_descendant`),
    INDEX `IDX_7a69302bc35bf787fd17ea067f` (`id_ancestor`),
    INDEX `IDX_0a663735b1c11c6dfa3ead92b9` (`id_descendant`),
    FOREIGN KEY (`id_ancestor`) REFERENCES `SUITES_DE_TESTE` (`id`) ON DELETE CASCADE,
    FOREIGN KEY (`id_descendant`) REFERENCES `SUITES_DE_TESTE` (`id`) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Insert initial values for environmental factors
INSERT INTO `FATORES_AMBIENTAIS` (`AMB_ID`, `AMB_DESCRICAO`, `AMB_PESO`) VALUES 
  (1, 'Familiaridade com o processo unificado', 1.5),
  (2, 'Experiência aplicação', 0.5),
  (3, 'Experiência com orientação a objetos', 1.0),
  (4, 'Capacidade de análise do líder de projeto', 0.5),
  (5, 'Motivação', 1.0),
  (6, 'Estabilidade dos requisitos', 2.0),
  (7, 'Consultores em tempo parcial', -1.0),
  (8, 'Dificuldade de programação na Linguagem', -1.0);

-- Insert initial values for technical factors
INSERT INTO `FATORES_TECNICOS` (`TEC_ID`, `TEC_DESCRICAO`, `TEC_PESO`) VALUES 
  (1, 'Sistema distribuído', 2.0),
  (2, 'Desempenho da Aplicação', 1.0),
  (3, 'Eficiência do Usuário', 1.0),
  (4, 'Complexidade de Processamento', 1.0),
  (5, 'Reusabilidade de Código', 1.0),
  (6, 'Facilidade de instalação', 0.5),
  (7, 'Facilidade de uso', 0.5),
  (8, 'Portabilidade', 2.0),
  (9, 'Facilidade de mudança', 1.0),
  (10, 'Concorrência', 1.0),
  (11, 'Características de segurança', 1.0),
  (12, 'Acesso a Dispositivos de Terceiros', 1.0),
  (13, 'Requer Treinamento aos Usuários', 1.0); 